server:
  port: 8081

graphql:
  servlet:
    mapping: /graphql
    enabled: true
  websocket:
    path: /graphql
    enabled: true
  tools:
    schema-location-pattern: "classpath:graphql/**/*.graphqls"  # Enables nested folders too

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true