server:
  port: 80

graphql:
  servlet:
    mapping: /graphql
    enabled: true
  tools:
    schema-location-pattern: "classpath:graphql/**/*.graphqls"  # Enables nested folders too

spring:
  graphql:
    websocket:
      path: /graphql
      enabled: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true